// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhIiC4grg16Zjzx5AxMo7WH82JrmE3TQ',
    appId: '1:454743031932:web:d7d78cc6e1613c668849f9',
    messagingSenderId: '454743031932',
    projectId: 'heartrackv1',
    authDomain: 'heartrackv1.firebaseapp.com',
    storageBucket: 'heartrackv1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsv0U4IrsBv5DWZMJO2Or91jz3xK1tc-E',
    appId: '1:454743031932:android:706790764d375b3c8849f9',
    messagingSenderId: '454743031932',
    projectId: 'heartrackv1',
    storageBucket: 'heartrackv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBfDUhEY9hqhSlsWQeWismVcodlzcH3qE',
    appId: '1:454743031932:ios:2d6939b0444510408849f9',
    messagingSenderId: '454743031932',
    projectId: 'heartrackv1',
    storageBucket: 'heartrackv1.firebasestorage.app',
    iosBundleId: 'com.example.heartrackV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBfDUhEY9hqhSlsWQeWismVcodlzcH3qE',
    appId: '1:454743031932:ios:2d6939b0444510408849f9',
    messagingSenderId: '454743031932',
    projectId: 'heartrackv1',
    storageBucket: 'heartrackv1.firebasestorage.app',
    iosBundleId: 'com.example.heartrackV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwhIiC4grg16Zjzx5AxMo7WH82JrmE3TQ',
    appId: '1:454743031932:web:c7945ba7ca73df378849f9',
    messagingSenderId: '454743031932',
    projectId: 'heartrackv1',
    authDomain: 'heartrackv1.firebaseapp.com',
    storageBucket: 'heartrackv1.firebasestorage.app',
  );
}
